// <auto-generated />
using System;
using Domaine.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domaine.Migrations
{
    [DbContext(typeof(ScheduleFlowDBContexte))]
    [Migration("20260513195644_SeedUser")]
    partial class SeedUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Domaine.Context.Annonce", b =>
                {
                    b.Property<int>("AnnonceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Createur")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DatePublication")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AnnonceId");

                    b.ToTable("Annonces");
                });

            modelBuilder.Entity("Domaine.Context.DemandeConge", b =>
                {
                    b.Property<int>("DemandeCongeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Approbateur")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Raison")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeConge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DemandeCongeID");

                    b.ToTable("DemandeConges");
                });

            modelBuilder.Entity("Domaine.Entity.CreneauDispo", b =>
                {
                    b.Property<int>("IdCreneau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FeuilleDispoIdFeuille")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeureDebut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeureFin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdFeuille")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdCreneau");

                    b.HasIndex("FeuilleDispoIdFeuille");

                    b.ToTable("CreneauDispos");
                });

            modelBuilder.Entity("Domaine.Entity.FeuilleDispo", b =>
                {
                    b.Property<int>("IdFeuille")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEmploye")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdFeuille");

                    b.ToTable("FeuilleDispos");
                });

            modelBuilder.Entity("Domaine.Entity.Quart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Heures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPub")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Quarts");
                });

            modelBuilder.Entity("Domaine.Entity.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourrielEntreprise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateNaissance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LienParente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomContactUrgence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTelephonePersonnel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTelephoneProfessionnel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionProvince")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelephoneContactUrgence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            IdUtilisateur = 1,
                            Adresse = "100 Rue de la Gauchetière",
                            CodePostal = "H3B 2S2",
                            Courriel = "Employeur@gmail.com",
                            CourrielEntreprise = "Employeur@gmail.com",
                            DateCreation = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = "13 janvier 1999",
                            Genre = "Mâle",
                            LienParente = "N/A",
                            MotDePasse = "1234",
                            Nom = "Galvary",
                            NomContactUrgence = "Durocher, Preta",
                            NumeroTelephonePersonnel = "514-540-420",
                            NumeroTelephoneProfessionnel = "514-555-0100",
                            Pays = "Canada",
                            Prenom = "Jean",
                            RegionProvince = "Québec",
                            Role = 1,
                            TelephoneContactUrgence = "911",
                            Ville = "Montréal"
                        },
                        new
                        {
                            IdUtilisateur = 2,
                            Adresse = "100 Rue de la Gauchetière",
                            CodePostal = "H3B 2S2",
                            Courriel = "Gerant@gmail.com",
                            CourrielEntreprise = "Gerant@gmail.com",
                            DateCreation = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = "13 janvier 1999",
                            Genre = "Mâle",
                            LienParente = "N/A",
                            MotDePasse = "1234",
                            Nom = "Dumets",
                            NomContactUrgence = "Durocher, Preta",
                            NumeroTelephonePersonnel = "514-540-420",
                            NumeroTelephoneProfessionnel = "514-555-0100",
                            Pays = "Canada",
                            Prenom = "Bertrand",
                            RegionProvince = "Québec",
                            Role = 0,
                            TelephoneContactUrgence = "911",
                            Ville = "Montréal"
                        },
                        new
                        {
                            IdUtilisateur = 3,
                            Adresse = "100 Rue de la Gauchetière",
                            CodePostal = "H3B 2S2",
                            Courriel = "Employe@gmail.com",
                            CourrielEntreprise = "Employe@gmail.com",
                            DateCreation = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateNaissance = "13 janvier 1999",
                            Genre = "Mâle",
                            LienParente = "N/A",
                            MotDePasse = "1234",
                            Nom = "Rognak",
                            NomContactUrgence = "Durocher, Preta",
                            NumeroTelephonePersonnel = "514-540-420",
                            NumeroTelephoneProfessionnel = "514-555-0100",
                            Pays = "Canada",
                            Prenom = "Claude",
                            RegionProvince = "Québec",
                            Role = 2,
                            TelephoneContactUrgence = "911",
                            Ville = "Montréal"
                        });
                });

            modelBuilder.Entity("Domaine.Entity.CreneauDispo", b =>
                {
                    b.HasOne("Domaine.Entity.FeuilleDispo", null)
                        .WithMany("creneauDispo")
                        .HasForeignKey("FeuilleDispoIdFeuille");
                });

            modelBuilder.Entity("Domaine.Entity.FeuilleDispo", b =>
                {
                    b.Navigation("creneauDispo");
                });
#pragma warning restore 612, 618
        }
    }
}
