// <auto-generated />
using System;
using Domaine.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domaine.Migrations
{
    [DbContext(typeof(ScheduleFlowDBContexte))]
    [Migration("20260504020325_RenommerPostEnPoste")]
    partial class RenommerPostEnPoste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Domaine.Context.DemandeConge", b =>
                {
                    b.Property<int>("IdConge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Approbateur")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Raison")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeConge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdConge");

                    b.ToTable("DemandeConges");
                });

            modelBuilder.Entity("Domaine.Entity.CreneauDispo", b =>
                {
                    b.Property<int>("IdCreneau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FeuilleDispoIdFeuille")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeureDebut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeureFin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdFeuille")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdCreneau");

                    b.HasIndex("FeuilleDispoIdFeuille");

                    b.ToTable("CreneauDispos");
                });

            modelBuilder.Entity("Domaine.Entity.FeuilleDispo", b =>
                {
                    b.Property<int>("IdFeuille")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEmploye")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdFeuille");

                    b.ToTable("FeuilleDispos");
                });

            modelBuilder.Entity("Domaine.Entity.Quart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Heures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPub")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Quarts");
                });

            modelBuilder.Entity("Domaine.Entity.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourrielEntreprise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateNaissance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LienParente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomContactUrgence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTelephonePersonnel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTelephoneProfessionnel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionProvince")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelephoneContactUrgence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUtilisateur");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Domaine.Entity.CreneauDispo", b =>
                {
                    b.HasOne("Domaine.Entity.FeuilleDispo", null)
                        .WithMany("creneauDispo")
                        .HasForeignKey("FeuilleDispoIdFeuille");
                });

            modelBuilder.Entity("Domaine.Entity.FeuilleDispo", b =>
                {
                    b.Navigation("creneauDispo");
                });
#pragma warning restore 612, 618
        }
    }
}
